// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3rdBuo4XK9J2l8vQ1pCIoAGHyy71cInA',
    appId: '1:599910257056:web:b40d2a3dfce067f77494c5',
    messagingSenderId: '599910257056',
    projectId: 'chatapp-3f4df',
    authDomain: 'chatapp-3f4df.firebaseapp.com',
    storageBucket: 'chatapp-3f4df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6AUA8ZSrbKQqCKZZ21ZzIbfSnC0UoI2s',
    appId: '1:599910257056:android:1d7517762b2b178c7494c5',
    messagingSenderId: '599910257056',
    projectId: 'chatapp-3f4df',
    storageBucket: 'chatapp-3f4df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoejJz5B4mwG2hKmm6i6WDI-9lEWOq7DA',
    appId: '1:599910257056:ios:802aa2a36faa8d3a7494c5',
    messagingSenderId: '599910257056',
    projectId: 'chatapp-3f4df',
    storageBucket: 'chatapp-3f4df.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoejJz5B4mwG2hKmm6i6WDI-9lEWOq7DA',
    appId: '1:599910257056:ios:0af45ba13c848bd87494c5',
    messagingSenderId: '599910257056',
    projectId: 'chatapp-3f4df',
    storageBucket: 'chatapp-3f4df.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
